### ISSUE TITLE
Unable to Delete Notes by IDs, Need to Investigate ID Storage

### ISSUE THREAD

**Issue by Saadullah-2004** [zoyasiddiqui/NoteNinja#17]
Problem:
Our current note deletion process relies on tracking notes by names, lacking a mechanism for efficient deletion using associated IDs. This limitation hinders precise note management. Notes are currently stored and identified solely by names, restricting our system's flexibility.

Suggested Approach:
To enable note deletion by IDs, we must first identify and modify the storage mechanism for note IDs. Investigate the codebase to understand how IDs are generated and stored. Implement a system to track notes by both names and IDs, ensuring this modification does not compromise existing functionalities. Integrate a mechanism for deleting notes using their associated IDs, validating the process to ensure seamless functionality.

Expected Outcome:
Upon successful implementation, users should seamlessly delete notes using their IDs, providing a more flexible and robust note management system. It is essential to conduct comprehensive testing to identify and address potential issues, document changes for future reference, and set a deadline for completing this investigation and implementation. Assign relevant team members for efficient resolution and implementation.

**Comment by zoyasiddiqui** [comment]
Issue has been resolved. 

## Note Entity Fix
I added the functionality for the setID and getID methods throughout the Note entity files. The attribute was there, but we had note actually implemented it yet.

## DAO Fix
I added functions to the NoteDataAccessObject which enabled us to actually work with the note ID.
